# Site settings
title: Emanuele Maso
description: Personal page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Emanuele Maso
user_description: I'm a Computer Science student at University of Udine who loves programming and design everything, in particular mobile apps.&nbsp;I worked as help desk and computer repair technician on a small store and as Junior Dev for 5 projects with a Web Developer.
user_title: Front-End Developer
email: emanuele.maso97@gmail.com
twitter_username: clarkstoro
github_username:  clarkstoro
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
